#!/usr/bin/env python3
"""Embed the committed web editor bundle as a C array.

Usage: gen_web_bundle.py <index.html.gz> <out.c>

The teensy41 target does this inside its PlatformIO pre-script
(scripts/build_core.py); the Daisy netlink Makefile runs this at parse
time instead. The output is only rewritten when the input is newer, so
incremental builds stay incremental.
"""

import os
import sys


def main() -> int:
    src, dst = sys.argv[1], sys.argv[2]
    if os.path.exists(dst) and os.path.getmtime(dst) >= max(
        os.path.getmtime(src), os.path.getmtime(__file__)
    ):
        return 0
    with open(src, "rb") as f:
        data = f.read()
    lines = [
        "/* Generated by gen_web_bundle.py from",
        f" * components/web_ui/www/dist/{os.path.basename(src)}; do not edit. */",
        "",
        "const unsigned char neon_web_index_gz[] = {",
    ]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"const unsigned int neon_web_index_gz_len = {len(data)};")
    lines.append("")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    # Write-then-rename so a failed run can never leave a fresh-looking
    # truncated output for the staleness check to trust.
    tmp = dst + ".tmp"
    with open(tmp, "w", encoding="ascii") as f:
        f.write("\n".join(lines))
    os.replace(tmp, dst)
    return 0


if __name__ == "__main__":
    sys.exit(main())
