# Compiles the repo's portable firmware core into the Teensy build, and
# embeds the committed web editor bundle.
#
# components/neon_core is plain C++17 with no platform includes (the host
# CI job enforces this), so it builds for the i.MX RT1062 unchanged. This
# script points the compiler at the same sources the ESP-IDF target and
# the host tests use instead of vendoring a copy that would drift. The
# shared app_state / ablink / webui headers come along the same way; the
# Teensy provides its own implementations in src/.

import os

Import("env")

repo_root = os.path.abspath(os.path.join(env["PROJECT_DIR"], ".."))
core_dir = os.path.join(repo_root, "components", "neon_core")
hal_dir = os.path.join(repo_root, "components", "neon_hal")
cjson_dir = os.path.join(repo_root, "third_party", "cjson")
link_dir = os.path.join(repo_root, "third_party", "link")

env.Append(
    CPPPATH=[
        os.path.join(core_dir, "include"),
        os.path.join(hal_dir, "include"),
        cjson_dir,
        # Shared service-layer headers (Teensy implementations in src/).
        os.path.join(repo_root, "components", "app_state", "include"),
        os.path.join(repo_root, "components", "ableton_link", "include"),
        # Ableton Link, with the teensy41 platform shadowing asio and the
        # platform selector (link_platform must come first).
        os.path.join(env["PROJECT_DIR"], "link_platform"),
        os.path.join(link_dir, "include"),
        # std::mutex / condition_variable shims for the gthread-less
        # toolchain (include_next reaches the real headers).
        os.path.join(env["PROJECT_DIR"], "stdshim"),
    ]
)

# Recursive: picks up src/*.cpp and src/audio/*.cpp. Platform default
# flags (-fno-exceptions included): neon_core neither throws nor sits
# between a Link throw and its catch — those all live in project TUs,
# which build_src_flags gives -fexceptions.
env.BuildSources(os.path.join("$BUILD_DIR", "neon_core"), os.path.join(core_dir, "src"))

# The one vendored C dependency (config_json.cpp needs it).
env.BuildSources(
    os.path.join("$BUILD_DIR", "cjson"), cjson_dir, src_filter="+<cJSON.c>"
)


# --- web editor bundle -------------------------------------------------
# The committed gzipped single-file app (kept current by CI) becomes a
# flash-resident C array; httpd_t41.cpp serves it with
# Content-Encoding: gzip, exactly like the ESP server.
def embed_web_bundle():
    bundle = os.path.join(
        repo_root, "components", "web_ui", "www", "dist", "index.html.gz"
    )
    gen_dir = os.path.join(env.subst("$BUILD_DIR"), "webgen")
    out = os.path.join(gen_dir, "web_bundle.cpp")
    os.makedirs(gen_dir, exist_ok=True)
    if (
        os.path.exists(out)
        and os.path.getmtime(out) >= os.path.getmtime(bundle)
    ):
        return gen_dir
    with open(bundle, "rb") as f:
        data = f.read()
    lines = [
        "// Generated by scripts/build_core.py from",
        "// components/web_ui/www/dist/index.html.gz — do not edit.",
        "#include <Arduino.h>",
        "extern const unsigned char neon_web_index_gz[] PROGMEM;",
        "extern const unsigned int neon_web_index_gz_len;",
        "const unsigned char neon_web_index_gz[] PROGMEM = {",
    ]
    for i in range(0, len(data), 16):
        chunk = ", ".join(str(b) for b in data[i : i + 16])
        lines.append("    " + chunk + ",")
    lines.append("};")
    lines.append(f"const unsigned int neon_web_index_gz_len = {len(data)};")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    return gen_dir


webgen_dir = embed_web_bundle()
env.BuildSources(os.path.join("$BUILD_DIR", "webgen_o"), webgen_dir)
